Scrap/Scrap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('seller/',include('sellers.urls')),
    path('vehicle/', include('Vehicle.urls')),
    path('accounts/', include('accounts.urls')),
    path('autoparts/', include('autoparts.urls')),
    path('customer/', include('customer.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

Scrap/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.sign_up, name="sign_up"),
    path('seller_signup/', views.seller_sign_up, name="seller_sign_up"),
    path('signin/', views.sign_in, name="sign_in"),
    path('logout/', views.log_out, name="log_out"),
]

Scrap/customer/urls.py
from django.urls import path
from . import views

app_name = "customer"

urlpatterns = [
    path("profile_customer/", views.profile_customer, name="profile_customer"),
    path("update_profile/", views.update_profile, name="update_profile"),
    path('cart/increase/<int:cart_item_id>/', views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:cart_item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path("cart/", views.view_cart, name="view_cart"),
    path("add_cart/<product_id>/", views.add_cart, name="add_cart"),
    path("remove_from_cart/<cart_item_id>/", views.remove_from_cart, name="remove_from_cart"),
    path('all/orders/', views.profile_customer, name='profile_customer'),

]

Scrap/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('form_example/', views.form_example, name="form_example"),
    path('content_example/', views.content_example, name="content_example"),
    path('contact/', views.contact_view, name="contact_view"),
]

Scrap/sellers/urls.py
from django.urls import path
from . import views

app_name = 'seller'

urlpatterns = [
    path('dashboard/', views.seller_dashboard, name='seller_dashboard'),
    # path('profile/<int:user_id>/', views.seller_profile_products, name='seller_profile_products'),
    path('add-product/', views.seller_add_product, name='seller_add_product'),
    path('update/<int:product_id>/', views.update_product, name='update_product'),
    # path('inventory/', views.seller_stock, name='seller_stock'),
    # path('delete/<int:product_id>/', views.seller_add_product, name='delete_product'),
    path('profile/<int:seller_id>/', views.seller_profile_view, name='seller_profile_view'),
    path('orders/', views.seller_order_list_view, name='seller_order_list_view'),
    path('orders/accept/<int:order_item_id>/', views.accept_order_item, name='accept_order_item'),
    path('orders/deny/<int:order_item_id>/', views.deny_order_item, name='deny_order_item'),
    path('accepted_orders/', views.accepted_order_list_view, name='accepted_order_list_view'),
    path('order_detail/<int:order_item_id>/', views.order_detail_view, name='order_detail_view'),
    path('order_detail/<int:order_item_id>/mark_delivered/', views.mark_as_delivered_view, name='mark_as_delivered_view'),
    path('delivered_history/', views.delivered_orders_history_view, name='delivered_orders_history_view'),
    path('checkout/', views.checkout, name='checkout'),

]

Scrap/main/models.py
from django.db import models

class Contact(models.Model):
   
    first_name = models.CharField(max_length=1024)
    username = models.CharField(max_length=15)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.first_name

Scrap/main/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'username', 'message']

Scrap/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from autoparts.models import Category
from django.contrib import messages
from .forms import ContactForm



# Create your views here.
def home_view(request: HttpRequest):
    categories = Category.objects.all()
    context = {"categories": categories}

    return render(request, "main/index.html", context)


def contact_view(request:HttpRequest):
    contact_form = ContactForm()
    
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, "تم ارسال رسالتك بنجاح!", "alert-success")
            return redirect('main:home_view')
        else:
            messages.error(request, "حدث خطأ اثناء الارسال", "alert-danger")
            return render(request, "main/contact.html")

    return render(request, 'main/contact.html')


def form_example(request: HttpRequest):

    return render(request, "main/form_example.html")



def content_example(request: HttpRequest):

    return render(request, "main/content_example.html")

Scrap/main/templates/main/base.html
{% load static %}
{% load custom_tags %}
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&family=Funnel+Display:wght@300..800&family=Fustat:wght@200..800&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Phudu&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Spicy+Rice&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <title>{% block title %}{% endblock %}</title>

    {% block style %}{% endblock %}
</head>
<body>
    <div class="wrapper d-flex flex-column justify-content-between">
        <header class="sticky-top">
            <nav class="navbar navbar-expand-lg pt-3 pb-3">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'main:home_view' %}">

                    <h3 class="fustat_heading">
                      <img src="{% static 'images/autoparts_logo.png' %}" alt="Logo" class="logo" style="height: 50px; margin-left: 10px;">
                      سكراب
                    </h3>

                  </a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'main:home_view' %}">الصفحة الرئيسة</a>
                      </li>
                        {% if request.user.is_authenticated and request.user|is_in_group_customer %}
                          <li class="nav-item d-flex">
                            <a href="{% url 'customer:profile_customer' %}">
                              <h5 class="text-white my-auto">
                              | مرحبا {{request.user.first_name}} |
                              <!-- request.user.username -->
                              </h5>
                            </a>
                            
                            <li class="nav-item">
                              <a class="nav-link active" href="{% url 'customer:view_cart' %}">سلة التسوق</a>
                            </li>

                            <li class="nav-item">
                              <a class="nav-link active" href="{% url 'customer:profile_customer' %}"> الطلبات</a>
                            </li>
                          </li>
                        
                        {% endif %}
                        {% if request.user.is_authenticated and request.user|is_in_group_seller %}
                          <li class="nav-item d-flex">
                            <a href="{% url 'seller:seller_profile_view' request.user.profileseller.id %}">
                              <h5 class="text-white my-auto">
                                | مرحبا {{request.user.profileseller.company_name}} |
                                <!-- request.user.username -->
                              </h5>
                            </a>

                            <li class="nav-item">
                              <a class="nav-link active" href="{% url 'seller:seller_profile_view' request.user.profileseller.id %}">صفحة البائع</a>
                            </li>

                            <li class="nav-item">
                              <a class="nav-link active" href="{% url 'seller:seller_add_product' %}">عرض قطعة جديدة  </a>
                            </li>

                            <li class="nav-item">
                              <a class="nav-link active" href="{% url 'seller:seller_dashboard' %}">ادارة المخزون </a>
                            </li>

                            <li class="nav-item">
                              <a class="nav-link active" href="{% url 'seller:seller_order_list_view' %}">ادارة الطلبات </a>
                            </li>

                            <li class="nav-item">
                              <a class="nav-link active" href="{% url 'seller:accepted_order_list_view' %}">طلبات التوصيل    </a>
                            </li>

                            <li class="nav-item">
                              <a class="nav-link active" href="{% url 'seller:delivered_orders_history_view' %}">الطلبات المسلّمة  </a>
                            </li>

                          </li>
                        {% endif %}

                        <!-- <li class="nav-item">
                          <a class="nav-link active" href="#">قطع الغيار</a>
                        </li> -->
                    
                        
                        {% if request.user.is_authenticated %}
                          <li class="nav-item">
                            <a class="nav-link active" href="{% url 'accounts:log_out' %}">تسجيل الخروج</a>
                          </li>
                        {% else %}
                          <li class="nav-item dropdown">
                            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              تسجيل الدخول للبائع
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="{% url 'accounts:seller_sign_up' %}">تسجيل عضوية جديدة</a></li>
                              <li><a class="dropdown-item" href="{% url 'accounts:sign_in' %}?next={{request.path}}">تسجيل الدخول</a></li>
                            </ul>
                          </li>

                  
                          <li class="nav-item dropdown">
                            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              تسجيل\تسجيل الدخول
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="{% url 'accounts:sign_up' %}">تسجيل عضوية جديدة</a></li>
                              <li><a class="dropdown-item" href="{% url 'accounts:sign_in' %}?next={{request.path}}">تسجيل الدخول</a></li>
                            </ul>
                          </li>
                        {% endif %}

                        <li class="nav-item">
                          <a class="nav-link active" href="{% url 'main:contact_view' %}">تواصل معنا</a>
                        </li>

                        <!-- 
                      <li class="nav-item" style="display: none;">
                        <a class="nav-link" href="#">تسجيل الخروج</a>
                      </li> -->
                      <!-- else  -->
                      <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          تسجيل الدخول
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <li><a class="dropdown-item" href="#">تسجيل الدخول</a></li>
                          <li><a class="dropdown-item" href="#">تسجيل عضوية جديدة</a></li>
                        </ul>
                      </li> -->
                      <!--  endif  -->
                    </ul>
                  </div>
                </div>
              </nav>
              {% if messages %}
                {% for message in messages %}
                  <div class="alert {{message.tags}} my-2 mx-2 alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                {% endfor %}
              {% endif %}
        </header>
        <main>


          {% block content %}
          
          {% endblock %}
        </main>
        <footer class="container-fluid p-2">
          <!-- <div class="container-fluid bg-custom text-white"> -->
            <p>© سكراب، جميع الحقوق محفوظة</p>
          <!-- </div>           -->
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
</body>
</html>

Scrap/main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block title %} Contact Us {% endblock %}

{% block content %}

{% load static %}

<div class="mt-5 d-flex flex-column justify-content-center align-items-center w-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-lg-8 transparent-bg">
                <div class="d-flex flex-column justify-content-start align-items-start">
                    <h2 class="m-0">املأ النموذج للتواصل</h2>
                </div>
                <div class="line mb-4"></div>

                <form class="d-flex flex-column gap-4" action="{% url 'main:contact_view' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="text" name="first_name" placeholder="الاسم الكامل" class="form-control" required/>
              
                    <input type="text" name="username" class="form-control" required placeholder="رقم الجوال" />
                    
                    <textarea name="message" placeholder="رسالتك" class="form-control" required style="height: 100px;"> </textarea>

                    <input type="submit" value="ارسل" class="btn" style="background-color: #fcd15c; color: black"/>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Scrap/main/templates/main/content_example.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}نموذج للمحتوى{% endblock %}

{% block style %}<link rel="stylesheet" href="{% static 'css/example.css' %}">{% endblock %}

{% block content %}
<section class="container">
   <h1>عنوان للسكشن الأول</h1>
   <div>محتوى تجريبي محتوى تجريبي محتوى تجريبي محتوى تجريبي</div>
</section>
<section class="container">
      <i class="bi bi-hammer"></i>
      <i class="bi bi-truck"></i>
      <i class="bi bi-wrench"></i>
      <i class="bi bi-wrench-adjustable"></i>
      <i class="bi bi-wrench-adjustable-circle"></i>
      <i class="bi bi-wrench-adjustable-circle-fill"></i>

      google
      <span class="material-symbols-outlined">
        handyman
        </span>
   <h1>عنوان للسكشن الثاني (محتوى مختلف عن السكشن الأول)</h1>
   <div>محتوى تجريبي محتوى تجريبي محتوى تجريبي محتوى تجريبي</div>
</section>
{% endblock %}

Scrap/main/templates/main/form_example.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}نموذج للفورم{% endblock %}

{% block style %}{% endblock %}

{% block content %}
 <section class="container">
     <div class="row">
         <div class="col-lg-8 col-md-12 form-center">
             <form action="#" method="post" enctype="multipart/form-data" class="d-flex flex-column gap-2">
                <h1>اضافة قطعة جديدة</h1>
                {% csrf_token %}
                <!-- start of text input -->
                <input type="text" name="name" class="form-control" placeholder="اسم القطعة" required />
                <!-- end of text input -->
                <!-- start of image input -->
                <div>
                    <h5>الصورة:</h5>
                    <input type="file" name="logo" class="form-control" accept="images/*" required>
                </div>
                <!-- end of image input -->
                <!-- start of Select dropdown -->
                <select name="brand" class="form-select" required>
                    <option value="">يرجى الاختيار</option>
                    <!-- for item in items -->
                    <option value="{{ brand.id }}">{{ brand.name }}</option>
                    <!-- endfor -->
                </select>
                <!-- end of Select dropdown -->
                <!-- start of Checkboxes -->
                <h5>الاختيارات:</h5>
                <div class="d-flex flex-wrap align-items-center gap-2">
                    <!-- for item in items -->
                    <div>
                        <input type="checkbox" name="name1" value="value1" id="id1" class="form-check-input" />
                        <label for="id1" class="check-label">البند الأول</label>
                    </div>
                    <!-- endfor -->
                </div>
                <!-- end of Checkboxes -->
                <textarea name="about" class="form-control" placeholder="نص طويل" required></textarea>
                <input type="submit" class="btn btn-custom" value="تسجيل">
            </form>
        </div>
    </div>
 </section>
{% endblock %}

Scrap/main/templates/main/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}سكراب | التشليح بين يديك{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<!-- hero section سكشن لعرض الهيرو -->
<section class="hero">
    <div class="row header-gif">
        <div class="col">
            <video autoplay loop muted>
                <source src="{% static 'videos/autoparts_promo.mp4' %}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
            <div class="col">
                <div class="hero-text-header d-flex flex-column justify-content-center align-items-center" style="height: 100%;"> 
                    <h1 class="hero-title-header">وفقًا للإحصائيات، تصل نسبة قطع غيار السيارات الصالحة للاستخدام الموجودة في مراكز التشليح إلى 70% من إجمالي المبيعات.</h1>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="hero">
    <div class="row row-cols-md-2">
        <div class="col  container-background2">
            <div class="hero-text div-custom d-flex flex-column text-center">
                
                <h1 class="hero-title">
                    
                    <!-- <div style="height: 50px; margin-left: 10px;"> 
                        <img src="{% static 'images/autoparts_logo.png' %}" alt="Logo" class="logo" style="height: 50px; margin-left: 10px;">
                    </div> -->
                    سكراب
                </h1>
                <p class="hero-text-p ">متجر متخصص لبيع وشراء قطع سيارات التشليح</p>
                
            </div>
        </div>
        <div class="col  container-background">
            <div class="hero-text div-custom d-flex flex-column text-center">
                <p class="hero-text-p2 mb-5"> التشليح صار لك اقرب! </p>
                <p class="hero-text-p">سجل عضويتك الآن وابدأ ببيع وشراء قطع سيارتك  </p>
                <a href="{% url 'accounts:seller_sign_up' %}" class="btn btn-light">
                    <h5>سجل عضوية بائع</h5>
                </a>
                <a href="{% url 'accounts:sign_up' %}" class="btn btn-light">
                    <h5>سجل عضوية مشتري</h5>
                </a>
            </div>
        </div>
    </div>
</section>
 <!-- autoparts section سكشن لعرض القطع الأساسية -->
<section class="container">
    <h1>اختر نوع القطعة</h1>
    <div>
        {% include 'autoparts/components/parts_list.html' %}
    </div>
</section>
{% endblock %}